# Generated by Django 4.2.4 on 2023-11-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_COL', models.CharField(max_length=100)),
                ('FathersName_COL', models.CharField(max_length=100)),
                ('Gender_COL', models.CharField(max_length=20)),
                ('Qualification_COL', models.CharField(max_length=100)),
                ('Institution_COL', models.CharField(max_length=200)),
                ('YearOfPassedOut_COL', models.IntegerField()),
                ('EmailID_COL', models.CharField(max_length=50)),
                ('MobileNumber_COL', models.BigIntegerField()),
                ('OptedField_COL', models.CharField(max_length=200)),
                ('OptedCourse_COL', models.CharField(max_length=200)),
                ('ModeOfClass_COL', models.CharField(max_length=10)),
                ('DateOfEntry_COL', models.CharField(max_length=50)),
            ],
        ),
    ]
